# Site settings
name: Senyer's Blog
email: 576085903@qq.com
author: 森
url: senyer.github.io
github: https://github.com/senyer/
baseurl: ""
description: java coder
meta_description: 森;blog;路漫漫其修远兮,吾将上下而求索
motto: It's our wits that make us men.
banner: 路漫漫其修远兮，吾将上下而求索。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: senyer

# Build settings
markdown: kramdown

baidu_analysis: 11dba7ac4288f5a7be1c484ef3262ce7

